name: Remote-SSH
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  SSH:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U tmate
      - name: SSH connection to Actions
        run: |
            python -m tmate

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: "github/Aeroxian"
          dst: "gitee/aeroxian"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "Aeroxian_Blog"
          force_update: true